name: tuff_osm
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - beautifulsoup4=4.9.3=pyhb0f4dca_0
  - brotlipy=0.7.0=py38h497a2fe_1001
  - bs4=4.9.3=0
  - cffi=1.14.6=py38ha65f79e_0
  - cryptography=3.4.7=py38ha5dfef3_0
  - geos=3.9.1=h9c3ff4c_2
  - idna=3.1=pyhd3deb0d_0
  - libblas=3.9.0=10_openblas
  - libcblas=3.9.0=10_openblas
  - libgcc-ng=11.1.0=hc902ee8_2
  - libgfortran-ng=11.1.0=h69a702a_0
  - libgfortran5=11.1.0=h6c583b3_0
  - libgomp=11.1.0=hc902ee8_2
  - liblapack=3.9.0=10_openblas
  - libopenblas=0.3.17=pthreads_h8fe5266_1
  - libstdcxx-ng=11.1.0=h56837e0_2
  - numpy=1.20.3=py38h9894fe3_0
  - pandas=1.3.1=py38h1abd341_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py38h578d9bd_3
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytz=2021.1=pyhd8ed1ab_0
  - selenium=3.141.0=py38h497a2fe_1002
  - shapely=1.7.1=py38haeee4fe_5
  - six=1.16.0=pyh6c4a22f_0
  - soupsieve=2.0.1=py_1
  - urllib3=1.26.6=pyhd8ed1ab_0
  - ca-certificates=2021.7.5=h06a4308_1
  - certifi=2021.5.30=py38h06a4308_0
  - et_xmlfile=1.1.0=py38h06a4308_0
  - jdcal=1.4.1=py_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - ncurses=6.2=he6710b0_1
  - openpyxl=3.0.7=pyhd3eb1b0_0
  - openssl=1.1.1k=h27cfd23_0
  - pip=21.1.3=py38h06a4308_0
  - python=3.8.10=h12debd9_8
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py38h06a4308_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
